### ISSUE TITLE
`modelpredict` is slightly less flexible than it used to be

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#27]
`modelpredict` is nice now in that if you only have stress+time or strain+time data it automatically knows which modulus to use. However, what about this (very common, pretty much canonical) example:

- user gets data into RheoTime struct
- fits a RheoModel to the data
- wants to predict new data based on fitted model to plot

Step 3 now requires a prior call to `extract` so that `modelpredict` knows which modulus to use. Perhaps there is a nice way to avoid this extra line of code as it is such a common workflow?

**Comment by akabla** [comment]
Hi Louis,

I think the code is clearer with the extraction step. The extraction could done when modelpredict is called, without naming a new variable:

maxwell_predict = modelpredict( extract(data, strain_only), maxwell_model )

I did agree with you that the keyword "strain_only" may benefit from a better name though.

We could also have a special keyword in model predict to combine with the extraction. I'm not opposed to this! but for clarity the keyword should relate to stress or strain, rather than modulus used, I think.

**Comment by moustachio-belvedere** [comment]
I will ask for a vote from @ab2425 as well, if she would like the convenience function you mentioned in your comment then I will add it. If not I won't as I don't mind too much eitherway.

**Comment by moustachio-belvedere** [comment]
I've come round to this way of doing it. I would prefer if there's only one (canonical) way of doing things so it should be this one.
