### ISSUE TITLE
Minor improvements to `RheoModelClass` outer constructor

### ISSUE THREAD

**Issue by moustachio-belvedere** [JuliaRheology/RHEOS.jl#52]
Migrated from definitions.jl comment:

Regarding `RheoModelClass` Constructor, add:

- [x] Define Null Expression, and make it default parameter
- [x] Model name and parameters should be required --> assert
- [x] info should have generic default value, such as "Model with $n params named $s..."

**Comment by akabla** [comment]
Name and params are now required by deleting their default value.
https://docs.julialang.org/en/v1/manual/functions/index.html#Keyword-Arguments-1

"If a keyword argument is not assigned a default value in the method definition, then it is required: an UndefKeywordError exception will be thrown if the caller does not assign it a value:

```
function f(x; y)
    ###
end
f(3, y=5) # ok, y is assigned
f(3)      # throws UndefKeywordError(:y)
```
"

**Comment by akabla** [comment]
Introducing null expressions for undefined moduli, rather than NaN, is not straight forward.

We need something in the moduli/compliance functionwrappers slots, and returning NaN seems appropriate. The easiest way to get there is to have a NaN expression to begin with.

We may want to reconsider how the "modulusexists" function works though, and how it is used in processing.jl. This utility function could look into the "expressions" named tuple as part of the RheoModelClass object and determine then if the modulus is defined, rather than evaluating the function. The external moduli/compliance functions could also check and send an error where appropriate.

**Comment by akabla** [comment]
I improved the content of the info field, but then commented it out to leave it an empty string by default. In fact, this string is only useful to provide extra info since the basic info is already visible:

```
julia> m = RheoModelClass(name="MyModel", p=[:x,:y])

Model name: MyModel

Free parameters: x and y

```

**Comment by moustachio-belvedere** [comment]
All sounds good to me
