### ISSUE TITLE
Interface to Python using PyJulia

### ISSUE THREAD

**Issue by akabla** [JuliaRheology/RHEOS.jl#78]
It would be nice to start thinking about how to make RHEOS available to python users and more.

There is a promising package called pyjulia which may help, but it is not working right now my machine.

https://github.com/JuliaPy/pyjulia

To be evaluated later then.

**Comment by moustachio-belvedere** [comment]
I wasn't previously able to get Julia calls from Python working on my Windows computer but it was a few years ago that I tried. I'll try again over the next week or so and report back how I get on in Windows. It would definitely be a cool feature/documentation section to have.

**Comment by akabla** [comment]
I got pyjulia to work a few months ago for basic calls, but I did not try with RHEOS. There is an issue right now (maybe specific to ubuntu) but hopefully, it'll work again soon. Feel free to give it a go and let us know!

**Comment by moustachio-belvedere** [comment]
I never got round to testing this, but I have been thinking about it more. What would the end goal be here? I'm happy to discuss further, but I don't think we should modify RHEOS source code to work around issues with PyJulia because as we've found out, it's already a significant cognitive burden just working around issues in native Julia packages (e.g. JLD2, functionwrappers).

If the end goal is more limited, such as adding a short section to the documentation which serves as a guide on how to do it, I would be more open to that. But in doing so we are making a commitment to keep that updated. (Relevant side-note: as of today, PyJulia is not tested against the last two stable releases of Python, 3.8 and 3.9).

I would bet that for most Python programmers who just want to use pure RHEOS functionality, without embedding it into some larger Python program, they will find it much easier and quicker to learn basic Julia and follow the RHEOS tutorials directly rather than trying to get inter-op working between languages. Python programmers advanced enough to be embedding RHEOS into a bigger application are probably independent enough to try and get inter-op working on their own.

**Comment by akabla** [comment]
I generally agree Louis. I would not be keen either to invest a lot at this point in PyJulia. Effort should be placed on maintaining the core, documenting, etc. It is difficult enough!

A simpler approach might be to build on the log feature and provide stand-alone tools to read a script and/or provide a simple GUI/WebUI interface. I think it is a manageable task from where we are. It would make the tool more accessible than a fiddly python binding.

**Comment by moustachio-belvedere** [comment]
I think we're in agreement on this then :) Lets create another issue for progress tracking of GUI once the project gets started.
